export interface CourseItem {
  id: string;
  title: string;
  description: string;
  duration: string;
  subModules: string[];
  domestic: string;
  international: string;
  keyHighlights: string[];
}

export const courses: CourseItem[] = [
  {
    id: 'computer-science',
    title: 'Computer Science (CS)',
    description: 'Build a strong foundation in programming, systems, and computing theory for software and technology careers.',
    duration: '3–4 years',
    subModules: [
      'Programming',
      'Data Structures',
      'Operating Systems',
      'Networks',
      'Databases',
      'Algorithms',
      'Theory of Computation',
    ],
    domestic: '£9,000–£63,000 / year',
    international: '$25,000–$70,000 / year',
    keyHighlights: ['Industry-aligned computing fundamentals', 'Strong software engineering foundations', 'Career-ready systems and algorithms training'],
  },
  {
    id: 'software-engineering',
    title: 'Software Engineering',
    description: 'Learn modern delivery practices for building reliable web, mobile, and enterprise applications.',
    duration: '3–4 years',
    subModules: [
      'Software Design',
      'Agile Development',
      'Web Development',
      'Mobile Apps',
      'DevOps',
      'Testing',
      'Architecture',
    ],
    domestic: '£9,000–£60,000 / year',
    international: '$25,000–$70,000 / year',
    keyHighlights: ['Professional development workflows', 'Modern application delivery', 'Quality and test automation focus'],
  },
  {
    id: 'data-science',
    title: 'Data Science',
    description: 'Turn data into insight with analytics, visualization, and practical machine learning workflows.',
    duration: '3–4 years',
    subModules: [
      'Statistics',
      'Python',
      'Data Mining',
      'Big Data',
      'Visualization',
      'Machine Learning basics',
    ],
    domestic: '£10,000–£65,000 / year',
    international: '$25,000–$80,000 / year',
    keyHighlights: ['Data-driven decision making', 'End-to-end analytics pipelines', 'Hands-on model building'],
  },
  {
    id: 'artificial-intelligence',
    title: 'Artificial Intelligence (AI)',
    description: 'Explore advanced AI techniques for model development, automation, and real-world deployment.',
    duration: '3–4 years',
    subModules: [
      'Machine Learning',
      'Deep Learning',
      'Neural Networks',
      'NLP',
      'Computer Vision',
      'Reinforcement Learning',
    ],
    domestic: '£10,000–£70,000 / year',
    international: '$30,000–$90,000 / year',
    keyHighlights: ['Advanced AI workflows', 'Research-ready model techniques', 'Business-ready AI deployment'],
  },
  {
    id: 'cyber-security',
    title: 'Cyber Security',
    description: 'Develop defensive and ethical hacking skills to protect systems, networks, and digital infrastructure.',
    duration: '3–4 years',
    subModules: [
      'Ethical Hacking',
      'Cryptography',
      'Network Security',
      'Digital Forensics',
      'Malware Analysis',
    ],
    domestic: '£8,000–£60,000 / year',
    international: '$20,000–$60,000 / year',
    keyHighlights: ['Security-first engineering discipline', 'Protect real-world infrastructure', 'Threat detection and response'],
  },
  {
    id: 'information-technology',
    title: 'Information Technology (IT)',
    description: 'Master operational IT, cloud systems, and service delivery for modern digital environments.',
    duration: '3 years',
    subModules: [
      'IT Infrastructure',
      'Cloud Computing',
      'System Administration',
      'Networking',
      'Database Management',
    ],
    domestic: '£8,000–£50,000 / year',
    international: '$20,000–$50,000 / year',
    keyHighlights: ['Operational IT excellence', 'Cloud-first infrastructure', 'Service delivery capability'],
  },
  {
    id: 'computer-engineering',
    title: 'Computer Engineering',
    description: 'Bridge hardware and software through embedded systems, electronics, robotics, and IoT design.',
    duration: '4 years',
    subModules: [
      'Digital Electronics',
      'Microprocessors',
      'Embedded Systems',
      'Computer Architecture',
      'IoT',
      'Robotics',
    ],
    domestic: '£10,000–£65,000 / year',
    international: '$25,000–$70,000 / year',
    keyHighlights: ['Hardware-software integration', 'IoT and robotics design', 'Performance engineering'],
  },
  {
    id: 'game-development',
    title: 'Game Development / Multimedia',
    description: 'Create immersive digital experiences through game design, graphics, animation, and interactive media.',
    duration: '3–4 years',
    subModules: [
      'Game Design',
      'Unity/Unreal',
      '3D Graphics',
      'Animation',
      'UI/UX',
      'Interactive Media',
    ],
    domestic: '£8,000–£55,000 / year',
    international: '$15,000–$60,000 / year',
    keyHighlights: ['Creative digital experiences', 'Interactive storytelling', 'Immersive media development'],
  },
  {
    id: 'ai-specializations',
    title: 'AI Specializations (Advanced)',
    description: 'Advance into specialist AI leadership, generative systems, and ethical strategic design.',
    duration: '1–2 years (MSc level)',
    subModules: [
      'Advanced Machine Learning',
      'AI Research',
      'Robotics AI',
      'Generative AI',
      'LLMs',
      'AI Ethics',
    ],
    domestic: '£12,000–£80,000 / year',
    international: '$30,000–$120,000 / year',
    keyHighlights: ['Executive AI leadership', 'LLM and generative systems', 'Ethical and strategic AI design'],
  },
  {
    id: 'business-analytics',
    title: 'Business Analytics',
    description: 'Use data, forecasting, and decision science to solve real business problems and drive growth.',
    duration: '3 years',
    subModules: [
      'Business Intelligence',
      'SQL & Reporting',
      'Forecasting',
      'Optimization',
      'Strategy Analytics',
    ],
    domestic: '£8,000–£55,000 / year',
    international: '$20,000–$60,000 / year',
    keyHighlights: ['Analytical decision making', 'Executive reporting skills', 'Practical business insights'],
  },
  {
    id: 'cloud-computing',
    title: 'Cloud Computing',
    description: 'Build and manage modern cloud platforms, automation, and scalable digital infrastructure.',
    duration: '3–4 years',
    subModules: [
      'Cloud Architecture',
      'DevOps',
      'Containerization',
      'Automation',
      'Security Operations',
    ],
    domestic: '£9,000–£62,000 / year',
    international: '$24,000–$70,000 / year',
    keyHighlights: ['Scalable cloud engineering', 'Modern automation practices', 'Enterprise platform knowledge'],
  },
  {
    id: 'blockchain-and-web3',
    title: 'Blockchain & Web3',
    description: 'Explore decentralized systems, smart contracts, and secure digital asset applications.',
    duration: '3 years',
    subModules: [
      'Distributed Ledger Systems',
      'Smart Contracts',
      'Cryptography',
      'Web3 Applications',
      'Security',
    ],
    domestic: '£8,500–£58,000 / year',
    international: '$22,000–$65,000 / year',
    keyHighlights: ['Emerging technology training', 'Decentralized application design', 'Secure blockchain engineering'],
  },
  {
    id: 'product-design',
    title: 'Product Design',
    description: 'Create user-centered digital products with research, prototyping, and interaction design expertise.',
    duration: '3 years',
    subModules: [
      'UX Research',
      'Wireframing',
      'Prototyping',
      'UI Systems',
      'Design Thinking',
    ],
    domestic: '£7,500–£52,000 / year',
    international: '$18,000–$58,000 / year',
    keyHighlights: ['Human-centered design', 'Rapid prototyping skills', 'Cross-functional product thinking'],
  },
];
