export interface CourseItem {
  id: string;
  title: string;
  description: string;
  duration: string;
  subModules: string[];
  domestic: string; // Keep as fallback fullFee compatibility
  international: string; // Keep as fallback payableFee compatibility
  keyHighlights: string[];
  // New visual card fields
  rating: number;
  ratingsCount: number;
  attendees: number;
  startDate: string;
  fullFee: string;
  payableFee: string;
  discount: string;
  institution: string;
  deliveryMethod: string;
}

export const courses: CourseItem[] = [
  {
    id: 'ai-basics-for-productivity',
    title: 'AI Basics for Productivity',
    description: 'Master fundamental AI tools and workflows to automate daily tasks, generate content, and double your personal productivity.',
    duration: '6 - 8 Months',
    subModules: [
      'Introduction to Generative AI & Large Language Models',
      'Mastering ChatGPT & Gemini for Daily Tasks',
      'Prompt Engineering Basics & Practical Templates',
      'Automating Workflows with AI & Everyday Apps',
    ],
    domestic: '$2,000.00',
    international: '$1,500.00',
    keyHighlights: ['Personalized productivity templates', 'Prompt optimization cheatsheet', 'Hands-on workflow automation'],
    rating: 4.7,
    ratingsCount: 86,
    attendees: 114,
    startDate: '11 Aug 2026',
    fullFee: '$2,000.00',
    payableFee: '$1,500.00',
    discount: '-$500',
    institution: 'AIXX ACADEMY',
    deliveryMethod: 'Self-Paced E-Learning',
  },
  {
    id: 'artificial-intelligence-ai-for-boosting-productivity',
    title: 'Artificial Intelligence (AI) for Boosting Productivity',
    description: 'A fast-paced guide to leveraging pre-built AI assistants, templates, and systems to streamline operations and enhance work efficiency.',
    duration: '3 - 4 Months',
    subModules: [
      'AI Assistant Landscape & Productivity Foundations',
      'Email & Communication Automation Systems',
      'Document Summarization, Processing, & Data Extraction',
      'Automating Meeting Transcripts & Creating Action Items',
    ],
    domestic: '$300.00',
    international: '$225.00',
    keyHighlights: ['Quick-start template library', 'Integration guides for popular tools', 'Real-world productivity audits'],
    rating: 4.5,
    ratingsCount: 42,
    attendees: 98,
    startDate: '18 Aug 2026',
    fullFee: '$300.00',
    payableFee: '$225.00',
    discount: '-$75',
    institution: 'AIXX ACADEMY',
    deliveryMethod: 'Live Virtual',
  },
  {
    id: 'introduction-to-ai-and-machine-learning',
    title: 'Introduction to AI and Machine Learning',
    description: 'Learn the core concepts of artificial intelligence, supervised vs. unsupervised learning, and build your first predictive models.',
    duration: '9 - 12 Months',
    subModules: [
      'Fundamentals of Artificial Intelligence & Mathematical Concepts',
      'Supervised vs. Unsupervised Learning Paradigms',
      'Linear Regression & Classification Algorithms',
      'Model Evaluation, Feature Selection, & Hands-on Labs',
    ],
    domestic: '$320.00',
    international: '$240.00',
    keyHighlights: ['Foundational ML theory', 'Hands-on dataset modeling', 'Code-along lab sessions'],
    rating: 4.8,
    ratingsCount: 104,
    attendees: 167,
    startDate: '25 Aug 2026',
    fullFee: '$320.00',
    payableFee: '$240.00',
    discount: '-$80',
    institution: 'AIXX ACADEMY',
    deliveryMethod: 'In-Person Campus',
  },
  {
    id: 'introduction-to-artificial-intelligence-machine-learning',
    title: 'Introduction to Artificial Intelligence and Machine Learning',
    description: 'Gain foundational theoretical and practical knowledge of machine learning algorithms, deep neural networks, and their industry applications.',
    duration: '12 - 15 Months',
    subModules: [
      'Advanced Algorithms & Statistical Analysis',
      'Foundations of Artificial Neural Networks (ANNs)',
      'Introduction to Deep Learning & Backpropagation',
      'Real-world Industry Case Studies & Deployment Patterns',
    ],
    domestic: '$235.00',
    international: '$176.25',
    keyHighlights: ['In-depth model evaluations', 'Introduction to Deep Learning', 'Real-world corporate case studies'],
    rating: 4.6,
    ratingsCount: 61,
    attendees: 89,
    startDate: '01 Sep 2026',
    fullFee: '$235.00',
    payableFee: '$176.25',
    discount: '-$58.75',
    institution: 'AIXX ACADEMY',
    deliveryMethod: 'Self-Paced E-Learning',
  },
  {
    id: 'harnessing-generative-artificial-intelligence',
    title: 'Harnessing Generative Artificial Intelligence',
    description: 'An advanced masterclass on fine-tuning LLMs, retrieval-augmented generation (RAG), and building production-ready generative AI solutions.',
    duration: '18 - 24 Months',
    subModules: [
      'Attention Mechanism & Transformer Architectures',
      'Fine-Tuning & Customizing Large Language Models (LLMs)',
      'Building Retrieval-Augmented Generation (RAG) Pipelines',
      'Vector Databases, Semantic Search, & Embeddings',
      'Deploying GenAI Apps, Scalability, & Ethical Security',
    ],
    domestic: '$3,000.00',
    international: '$2,250.00',
    keyHighlights: ['End-to-end RAG architecture design', 'LLM fine-tuning techniques', 'Enterprise-grade security guidelines'],
    rating: 4.9,
    ratingsCount: 156,
    attendees: 210,
    startDate: '08 Sep 2026',
    fullFee: '$3,000.00',
    payableFee: '$2,250.00',
    discount: '-$750',
    institution: 'AIXX ACADEMY',
    deliveryMethod: 'Live Virtual',
  },
  {
    id: 'introduction-to-generative-artificial-intelligence-ai',
    title: 'Introduction to Generative Artificial Intelligence (AI)',
    description: 'Understand the fundamentals of generative models (ChatGPT, Midjourney, etc.), prompt engineering best practices, and ethical implications.',
    duration: '6 - 8 Months',
    subModules: [
      'The Landscape of Generative AI Models (Text, Images, Audio)',
      'AI Art, Graphic Design & Image Generation Tools (Midjourney, DALL-E)',
      'Practical Prompt Engineering Tricks & Best Practices',
      'Responsible AI Design, Copyright, & Safety Guidelines',
    ],
    domestic: '$700.00',
    international: '$525.00',
    keyHighlights: ['Multi-modal model exploration', 'Advanced prompt engineering tricks', 'Responsible AI design guidelines'],
    rating: 4.6,
    ratingsCount: 78,
    attendees: 135,
    startDate: '15 Sep 2026',
    fullFee: '$700.00',
    payableFee: '$525.00',
    discount: '-$175',
    institution: 'AIXX ACADEMY',
    deliveryMethod: 'In-Person Campus',
  },
  {
    id: 'ai-for-business-leaders',
    title: 'AI for Business Leaders',
    description: 'A comprehensive guide to implementing AI strategies in enterprise environments without writing code.',
    duration: '6 - 8 Months',
    subModules: [
      'AI-Driven Business Strategy & Frameworks',
      'Deploying No-code AI Tools in Enterprise',
      'Change Management, Staff Training & AI Governance',
      'Calculating ROI & Metrics for Business AI Initiatives',
    ],
    domestic: '$400.00',
    international: '$300.00',
    keyHighlights: ['Executive implementation templates', 'Enterprise AI roadmap guides', 'Real-world deployment audits'],
    rating: 4.8,
    ratingsCount: 52,
    attendees: 75,
    startDate: '22 Aug 2026',
    fullFee: '$400.00',
    payableFee: '$300.00',
    discount: '-$100',
    institution: 'AIXX ACADEMY',
    deliveryMethod: 'Self-Paced E-Learning',
  },
  {
    id: 'generative-ai-masterclass',
    title: 'Generative AI Masterclass',
    description: 'Learn how to build, fine-tune, and deploy advanced generative AI models from scratch.',
    duration: '12 - 15 Months',
    subModules: [
      'Deep Dive into LLM Architecture & Mechanics',
      'Supervised Fine-Tuning (SFT) & RLHF Strategies',
      'Enterprise Deployment, Scaling, & Vector Search integration',
      'Multi-Modal GenAI (Audio, Video, Code) & RAG Systems',
    ],
    domestic: '$2,800.00',
    international: '$2,100.00',
    keyHighlights: ['Direct mentorship sessions', 'GPU-powered learning labs', 'Advanced model optimization techniques'],
    rating: 4.9,
    ratingsCount: 118,
    attendees: 154,
    startDate: '29 Aug 2026',
    fullFee: '$2,800.00',
    payableFee: '$2,100.00',
    discount: '-$700',
    institution: 'AIXX ACADEMY',
    deliveryMethod: 'Live Virtual',
  },
  {
    id: 'prompt-engineering-masterclass',
    title: 'Prompt Engineering Masterclass',
    description: 'The practice of designing effective prompts to improve the quality, accuracy, and relevance of AI-generated responses.',
    duration: '4 - 6 Months',
    subModules: [
      'Zero-shot, Few-shot & Chain-of-Thought Prompting',
      'Context Window Optimization & System Instructions',
      'Prompt Injection Defenses & Handling Hallucinations',
    ],
    domestic: '$500.00',
    international: '$375.00',
    keyHighlights: ['Advanced prompts repository', 'Anti-hallucination checklists', 'Multi-model optimization guides'],
    rating: 4.7,
    ratingsCount: 92,
    attendees: 215,
    startDate: '05 Sep 2026',
    fullFee: '$500.00',
    payableFee: '$375.00',
    discount: '-$125',
    institution: 'AIXX ACADEMY',
    deliveryMethod: 'In-Person Campus',
  },
  {
    id: 'ai-for-developers-data-analytics',
    title: 'AI for Developers & Data Analytics',
    description: 'The use of AI tools and techniques to enhance software development, automate tasks, analyze data, and generate valuable insights for decision-making.',
    duration: '9 - 12 Months',
    subModules: [
      'Integrating AI Coding Assistants (GitHub Copilot, Cursor)',
      'Automated Code Refactoring, Debugging & Testing with AI',
      'AI-Powered Data Cleaning, Wrangling & Visualization',
      'Building Predictive Analytics Models & Automated Reporting',
    ],
    domestic: '$640.00',
    international: '$480.00',
    keyHighlights: ['Developer-first code environments', 'Data science dashboard tools', 'Automation script catalogs'],
    rating: 4.6,
    ratingsCount: 71,
    attendees: 110,
    startDate: '12 Sep 2026',
    fullFee: '$640.00',
    payableFee: '$480.00',
    discount: '-$160',
    institution: 'AIXX ACADEMY',
    deliveryMethod: 'Self-Paced E-Learning',
  },
  {
    id: 'agentic-ai-systems',
    title: 'Agentic AI Systems',
    description: 'AI systems that can autonomously plan, make decisions, and perform tasks to achieve specific goals with minimal human intervention.',
    duration: '9 - 12 Months',
    subModules: [
      'Introduction to Autonomous Agents & Reasoning Loops',
      'Planning, Memory Systems & Reflection Frameworks',
      'External Tool Integrations (Web Search, APIs, Databases)',
      'Building Multi-Agent Collaborative Systems (LangGraph, CrewAI)',
    ],
    domestic: '$1,200.00',
    international: '$900.00',
    keyHighlights: ['State-of-the-art agent labs', 'Production-ready codebases', 'Autonomus system blueprints'],
    rating: 4.9,
    ratingsCount: 46,
    attendees: 64,
    startDate: '19 Sep 2026',
    fullFee: '$1,200.00',
    payableFee: '$900.00',
    discount: '-$300',
    institution: 'AIXX ACADEMY',
    deliveryMethod: 'Live Virtual',
  },
  {
    id: 'quantum-computing-for-ai-fundamentals',
    title: 'Quantum Computing for AI – Fundamentals',
    description: 'The study of using quantum computing principles to enhance AI by enabling faster processing and solving complex problems beyond the capability of traditional computers.',
    duration: '18 - 24 Months',
    subModules: [
      'Principles of Quantum Mechanics: Qubits, Superposition & Entanglement',
      'Designing Quantum Circuits & Quantum Gates',
      'Hybrid Classical-Quantum Architectures & Variational Algorithms',
      'Quantum Machine Learning (QML) Foundations & Future Outlook',
    ],
    domestic: '$1,800.00',
    international: '$1,350.00',
    keyHighlights: ['Access to quantum simulators', 'Cutting-edge algorithms research', 'Hybrid classical-quantum designs'],
    rating: 4.8,
    ratingsCount: 39,
    attendees: 51,
    startDate: '26 Sep 2026',
    fullFee: '$1,800.00',
    payableFee: '$1,350.00',
    discount: '-$450',
    institution: 'AIXX ACADEMY',
    deliveryMethod: 'In-Person Campus',
  },
];
