name: Auto Deploy

on:
  push:
    branches:
      - main  # or 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key (AIXX_DEPLOY_KEY)
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.AIXX_DEPLOY_KEY }}

    - name: Run deploy.sh on server
      env:
        AIXX_DEPLOY_PATH: /var/www/aixx/be-aixx
        AIXX_DEPLOY_HOST: 192.46.230.132
        AIXX_DEPLOY_USER: ubuntu
      run: |
        ssh -o StrictHostKeyChecking=no $AIXX_DEPLOY_USER@$AIXX_DEPLOY_HOST << EOF
          cd $AIXX_DEPLOY_PATH
          bash deploy.sh
        EOF
